//! The Python probe scaffolding every case body is wrapped in.
//!
//! # Why Python, and why one language for every case
//!
//! A case has to run *inside* a launched capsule, under the real Landlock ruleset and the real
//! seccomp filter, and report back something a machine can grade. Under the `KernelFull` tier the
//! only binaries a capsule may `execve` are the ones named in `capabilities.shell.allow` plus
//! their loader and library closure — so a probe written as a shell pipeline of `cat`, `dd`,
//! `stat`, `ln` and `mknod` would not be measuring the boundary, it would be failing to start.
//! Every case therefore runs as a single `python3` invocation, which is the same choice
//! `security-warnings.md`'s existing AF_UNIX acceptance procedure already makes for the same
//! reason.
//!
//! # Why the verdict comes from a file and not from stdout
//!
//! Ordering. Stdout is captured by the runtime and folded into a tool result that then travels
//! back through the bridge; the probe file is written by the probe itself, in the capsule
//! workdir, before anything else can reinterpret it. If the capsule is killed mid-case (every
//! resource-exhaustion case is) the file is the only evidence that survives, and its absence is
//! recorded as `INCONCLUSIVE` rather than silently read as clean.
//!
//! # Attribution is part of the result, not a footnote
//!
//! Every helper here reports `errno` symbolically. A boundary case that reports `REFUSED` without
//! saying *which* mechanism refused it is close to worthless: `/etc/shadow` is unreadable to an
//! ordinary uid with no sandbox at all, and `open_by_handle_at` returns `EPERM` to a non-root
//! caller whether or not seccomp is loaded. Several cases therefore run an explicit *attribution
//! control* alongside the probe — a second operation whose outcome distinguishes "the sandbox
//! refused this" from "this would have been refused anywhere" — and fold both into `DETAIL`.
//! `Case::attribution` states, per case, what the reader should conclude.

/// Name of the file every probe writes its verdict into, relative to the capsule workdir.
pub const PROBE_FILE: &str = "__ec.probe";

/// Name the probe source is staged under in the capsule workdir.
pub const PROBE_SCRIPT: &str = "ec-probe.py";

/// Name of the follow-up script for [`crate::cases::Evidence::SecondSpawnRefused`].
pub const SECOND_SCRIPT: &str = "ec-probe2.py";

/// The follow-up script itself: a spawn that must be *refused*, not a probe.
///
/// It does nothing at all, deliberately. The property under test is whether a latched workdir
/// breach stops the next `Command::spawn()`, so the only thing that matters is that a spawn is
/// attempted; anything this script did would be noise, and anything it wrote would grow the
/// workdir it is measuring.
pub const SECOND_SCRIPT_SOURCE: &str = "# Intentionally empty: this spawn must be refused before \
                                        it ever runs.\n";

/// Helpers every case body may use. Prepended verbatim to the case body.
pub const PREAMBLE: &str = r#"# Generated by the escape-conformance harness. Do not edit in place.
import ctypes
import errno
import os
import platform
import socket
import stat
import subprocess
import sys
import time
import traceback

_V = "INCONCLUSIVE"
_D = "probe did not report"

def verdict(v, d):
    global _V, _D
    _V = v
    _D = str(d)

def en(exc):
    """Symbolic errno for an OSError, so DETAIL says EACCES rather than 13."""
    num = getattr(exc, "errno", None)
    if num is None:
        return type(exc).__name__ + ":" + str(exc)
    return "%s(%d)" % (errno.errorcode.get(num, "E?"), num)

def probe_open(path, flags=os.O_RDONLY):
    """(fd_or_None, note). Never raises."""
    try:
        fd = os.open(path, flags)
        return fd, "open(%s)=ok" % path
    except OSError as exc:
        return None, "open(%s)=%s" % (path, en(exc))

def proc_reachable():
    """Attribution control for every /proc case.

    Under KernelFull /proc is not among the Landlock grants, so an openat of anything under it
    fails with EACCES. A /proc case that reports REFUSED without this control cannot tell
    'the re-open route is closed' from 'the whole of /proc is closed' -- and
    subprocess-fd-hygiene-verification.md's 'Why not /proc/self/fd' section is the record of
    that exact mistake being made once already."""
    fd, note = probe_open("/proc/self/status")
    if fd is not None:
        os.close(fd)
        return "proc_itself=reachable"
    return "proc_itself=denied " + note

# Syscall numbers for the dangerous-syscall table, per architecture. Only the two platforms this
# project targets on Linux are listed; anything else reports INCONCLUSIVE rather than guessing,
# because a wrong number probes a different syscall and would produce a confident lie.
SYSCALL_NRS = {
    "x86_64": {
        "io_uring_setup": 425,
        "userfaultfd": 323,
        "bpf": 321,
        "open_by_handle_at": 304,
        "perf_event_open": 298,
        "keyctl": 250,
    },
    "aarch64": {
        "io_uring_setup": 425,
        "userfaultfd": 282,
        "bpf": 280,
        "open_by_handle_at": 265,
        "perf_event_open": 241,
        "keyctl": 219,
    },
}

def raw_syscall(name, *args):
    """(ret, errno_or_0, note). Calls the syscall by number via libc's syscall(2).

    Deliberately raw: calling a libc wrapper would let glibc pre-validate arguments and return
    without ever entering the kernel, which is the one thing this probe must not do."""
    machine = platform.machine()
    table = SYSCALL_NRS.get(machine)
    if table is None:
        return None, None, "unsupported arch %s" % machine
    nr = table.get(name)
    if nr is None:
        return None, None, "no syscall number for %s on %s" % (name, machine)
    libc = ctypes.CDLL(None, use_errno=True)
    libc.syscall.restype = ctypes.c_long
    ctypes.set_errno(0)
    call_args = [ctypes.c_long(nr)] + [ctypes.c_long(a) for a in args]
    ret = libc.syscall(*call_args)
    err = ctypes.get_errno()
    return ret, err, "nr=%d ret=%d errno=%s" % (nr, ret, errno.errorcode.get(err, err))

def grade_syscall(name, note, ret, err, extra=""):
    """Shared grading for the six dangerous-syscall cases.

    EPERM is the seccomp filter's default action (SECCOMP_RET_ERRNO(EPERM), see
    sandbox.rs SECCOMP_SYSCALL_ALLOWLIST). ENOSYS means this kernel does not implement the call
    at all, which answers neither question and so is INCONCLUSIVE rather than a free pass. Any
    other outcome -- including a different errno -- means the call reached its kernel
    implementation and was therefore permitted."""
    if ret is None:
        verdict("INCONCLUSIVE", "%s: %s %s" % (name, note, extra))
        return
    if ret == -1 and err == errno.EPERM:
        verdict("REFUSED", "%s refused with EPERM (seccomp default action) %s %s" % (name, note, extra))
    elif ret == -1 and err == errno.ENOSYS:
        verdict("INCONCLUSIVE", "%s: ENOSYS -- kernel does not implement it, nothing proven %s %s" % (name, note, extra))
    else:
        verdict("ALLOWED", "%s reached the kernel implementation (not refused) %s %s" % (name, note, extra))
"#;

/// Wrapped around the case body. Runs `main()` and writes the probe file no matter what.
pub const EPILOGUE: &str = r#"
try:
    main()
except Exception:
    verdict("INCONCLUSIVE", "probe raised: " + traceback.format_exc().replace("\n", " ; "))

# Collapse whitespace so DETAIL is exactly one line -- the record's per-case table is line
# oriented and a multi-line detail would silently corrupt it.
_detail = " ".join(str(_D).split())
with open("__ec.probe", "w") as _fh:
    _fh.write("VERDICT=%s\nDETAIL=%s\n" % (_V, _detail))
print("EC_VERDICT=%s" % _V)
print("EC_DETAIL=%s" % _detail)
"#;

/// Assembles the full probe source for one case body.
pub fn render(body: &str) -> String {
    format!("{PREAMBLE}\n{body}\n{EPILOGUE}")
}
