#!/bin/sh
# install-dev-apparmor.sh — give a checkout build of `mur` the same narrow
# user-namespace grant the shipped profile gives an installed one.
#
# `packaging/apparmor/mur-sealed` attaches to installed paths (/usr/local/bin/mur,
# ~/.local/bin/mur, …). A binary built out of a checkout lives at
# ./target/debug/mur or ./target/release/mur, which no shipped profile names, so on
# a stock Ubuntu 23.10+ host — where kernel.apparmor_restrict_unprivileged_userns is
# 1 by default — a from-source `mur` cannot create a user namespace and cannot reach
# `capabilities.containment: sealed`. This generates a second, separate profile for
# exactly this checkout's two target paths.
#
# It is the alternative to `sysctl -w kernel.apparmor_restrict_unprivileged_userns=0`,
# which works but removes unprivileged-userns hardening from every program on the
# machine rather than from one binary. `mur doctor` reports which of the two is in
# effect (warning[W-SEC-013] for the sysctl).
#
# Usage:
#     scripts/install-dev-apparmor.sh --print    # write the profile to stdout, touch nothing
#     sudo scripts/install-dev-apparmor.sh       # parse-check, install, load
#
# Installs to /etc/apparmor.d/mur-sealed-dev — a separate top-level file, never
# /etc/apparmor.d/local/mur-sealed, which is included *inside* the shipped profiles
# and therefore cannot declare a new profile of its own.

set -eu

PROFILE_NAME="mur-sealed-dev"
PROFILE_PATH="/etc/apparmor.d/${PROFILE_NAME}"

usage() {
    cat <<'USAGE'
usage: install-dev-apparmor.sh [--print] [--help]

  --print   write the generated profile to stdout and exit; nothing is written
            under /etc, no profile is loaded, and no privilege is needed
  --help    this message

With no flags, parse-checks the generated profile with `apparmor_parser -Q`,
installs it to /etc/apparmor.d/mur-sealed-dev and loads it with
`apparmor_parser -r`. Needs root; this script never invokes sudo itself.
USAGE
}

print_only=0
while [ $# -gt 0 ]; do
    case "$1" in
        --print) print_only=1 ;;
        -h|--help) usage; exit 0 ;;
        *) printf 'install-dev-apparmor.sh: unknown argument %s\n\n' "$1" >&2; usage >&2; exit 2 ;;
    esac
    shift
done

script_dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
repo_root="$(CDPATH= cd -- "${script_dir}/.." && pwd)"

# AppArmor attachment specifications are whitespace-delimited, so a checkout under a
# path containing a space cannot be named in one. Say so rather than emitting a
# profile that attaches to something else.
case "$repo_root" in
    *[[:space:]]*)
        printf 'install-dev-apparmor.sh: the checkout path contains whitespace (%s), which an AppArmor attachment specification cannot express. Move or symlink the checkout to a path without spaces.\n' \
            "$repo_root" >&2
        exit 1
        ;;
esac

generate_profile() {
    cat <<PROFILE
# ${PROFILE_NAME} — generated by scripts/install-dev-apparmor.sh. Do not edit; re-run
# the script instead. Regenerate after moving the checkout: the attachment below is
# an absolute path, and AppArmor matches on the path, not on the file.
#
# Grants exactly what packaging/apparmor/mur-sealed grants an installed mur, to the
# two binaries this checkout builds. The profile name begins with "mur-sealed", which
# is what the runtime's /proc/self/attr/current probe matches on.
#
# Checkout: ${repo_root}
#
# Remove with:
#     sudo apparmor_parser -R ${PROFILE_PATH} && sudo rm ${PROFILE_PATH}

abi <abi/4.0>,

include <tunables/global>

profile ${PROFILE_NAME} ${repo_root}/target/{debug,release}/mur flags=(unconfined) {
  # The one rule that matters: do not transition into \`unprivileged_userns\` when
  # this binary calls unshare(CLONE_NEWUSER).
  userns,

  # Stated explicitly even though \`flags=(unconfined)\` already permits them, so this
  # file documents the same privileged-operation set the shipped profile documents.
  capability sys_admin,
  capability net_admin,
  mount,
  umount,
  pivot_root,

  include if exists <local/${PROFILE_NAME}>
}
PROFILE
}

if [ "$print_only" -eq 1 ]; then
    generate_profile
    exit 0
fi

# A host with no AppArmor needs no profile and loses nothing by having none — the
# same case packaging/apparmor/mur-sealed documents. Nothing to do, and that is not
# a failure.
if [ ! -d /sys/module/apparmor ]; then
    printf 'AppArmor is not enabled on this host, so nothing restricts unprivileged user namespaces and no profile is needed. Nothing was installed.\n'
    exit 0
fi

if ! command -v apparmor_parser >/dev/null 2>&1; then
    printf 'install-dev-apparmor.sh: AppArmor is enabled but apparmor_parser was not found. Install the AppArmor userspace tools (Debian/Ubuntu: apparmor-utils) and re-run.\n' >&2
    exit 1
fi

if [ "$(id -u)" != "0" ]; then
    printf 'install-dev-apparmor.sh: writing %s and loading it needs root, and this script never invokes sudo. Run:\n  sudo %s/scripts/install-dev-apparmor.sh\n' \
        "$PROFILE_PATH" "$repo_root" >&2
    exit 1
fi

tmp_profile="$(mktemp)"
trap 'rm -f "$tmp_profile"' EXIT INT TERM
generate_profile >"$tmp_profile"

# Parse-check before writing: an unparseable file in /etc/apparmor.d makes every
# later `apparmor_parser -r` of the whole directory fail, so it must never land.
if ! apparmor_parser -Q "$tmp_profile"; then
    printf 'install-dev-apparmor.sh: the generated profile did not parse, so nothing was written to %s.\n' \
        "$PROFILE_PATH" >&2
    exit 1
fi

install -m 644 "$tmp_profile" "$PROFILE_PATH"
apparmor_parser -r "$PROFILE_PATH"

printf 'Installed and loaded %s for %s/target/{debug,release}/mur.\n' "$PROFILE_PATH" "$repo_root"
printf 'Verify:  %s/target/debug/mur doctor        # expect userns grant: profile_confining\n' "$repo_root"
printf 'Remove:  sudo apparmor_parser -R %s && sudo rm %s\n' "$PROFILE_PATH" "$PROFILE_PATH"
